<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("../php/constants.php");
            include(_PHP . "/menus.php");
            include(_PHP . "/under_construction.php");
        
        ?>
		<meta charset="UTF-8">
		<title>MICHAEL KUBIAK - Dehumidifier Control Project</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Dehumidifier Control" content="" id = "name"/>
		<?php
			foreach (getFileLists(["css"], _CSS) as $file){
                echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/$file[basename]'>";
            }
			echo "<script src=" . _JS . "/menus.js></script>";
			echo "<script src=" . _JS . "/buttons.js></script>";
            $pages = getFileLists(["phtml"]);
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);under_construction()?>

        <script type="text/javascript">
            checkCookies("<?php echo _ROOT?>");
        </script>		
	</body>
</html>
