<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("../php/constants.php");
            include(_PHP . "/menus.php");
            include(_PHP . "/under_construction.php");
        
        ?>
		<meta charset="UTF-8">
		<title>MICHAEL KUBIAK - Enzyme Classifier Project</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Enzyme Classifier" content="" id = "name"/>
		<?php
			foreach (getFileLists(["css"], _CSS) as $file){
                echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/$file[basename]'>";
            }
			echo "<script src=" . _JS . "/menus.js></script>";
			echo "<script src=" . _JS . "/buttons.js></script>";
            $pages = getFileLists(["phtml"]);
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);under_construction()?>

<section>
            <?php startCollapsible("Origin")?>
                <h2 class=sectionheading>Origins of the Project</h2> 
                <small id=show>(show)</small>
                <small id=hide class=hide>(hide)</small>
            </div>
            <div class=inside>
                <p>
                    This project started as my individual project for my <a href=../CV/education.phtml#indiv onclick='linkToCollapsible("indiv", "/CV");linkToCollapsible("bioinf", "/CV")'> masters course </a> 
                </p>
            </div>
        </section>
        
        <hr style="height:3px; background-color:grey">
        <script type="text/javascript">
            checkCookies("<?php echo _ROOT?>");
        </script>		
	</body>
</html>
