<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("./php/constants.php");
            include(_PHP . "/menus.php");
        
        ?>
		<meta charset="UTF-8">
		<title>MICHAEL KUBIAK - Contact Me</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Contact Me" content="" id = "name"/>
		<?php
			foreach (getFileLists(["css"], _CSS) as $file){
                echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/$file[basename]'>";
            }
			echo "<script src=" . _JS . "/menus.js></script>";
            echo "<script src=" . _JS . "/buttons.js></script>";
            $pages = getFileLists(["phtml"]);
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);?>
		<p>If you would like to offer me a job, or let me know about any problems with this website, please don't hesitate to contact me:</p>
        <hr>
        <div class=centre>
            <p><strong>Mobile:</strong> <a href= tel: +447956960722>07956 960722</a></p>
            <p><strong>Email:</strong> <a href= mailto: michael.kubiak@bath.edu>michael.kubiak@bath.edu</a></p>
            <p><strong>LinkedIn:</strong> <a href=https://www.linkedin.com/in/m-i-c-h-a-e-l-kubiak target=_blank>www.linkedin.com/in/m-i-c-h-a-e-l-kubiak</a></p>
            <p><strong>Address:</strong></p>
            <p>Bwthyn Cadwen</p>
            <p>Pen-y-cae-Mawr</p>
            <p>Wentwood</p>
            <p>Usk</p>
            <p>NP15 1NA</p>
        </div>
        
        <script type="text/javascript">
            checkCookies("<?php echo _ROOT?>");
        </script>
	</body>
</html>
