<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("./php/constants.php");
            include(_PHP . "/menus.php");
        
        ?>
		<meta charset="UTF-8">
		<title>Michael Kubiak - Homepage</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Homepage" content="" id="name"/>
		<?php
            foreach (getFileLists(["css"], _CSS) as $file){
                echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/$file[basename]'>";
            }
            echo "<script src=" . _JS . "/menus.js></script>";
            echo "<script src=" . _JS . "/buttons.js></script>";
            $pages = getFileLists(["phtml"]);
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);?>
        <img src=<?php echo _IMG?>/me.jpg width = 20% class='right' style='margin-top:1%'>
        <h2>About me</h2>
        
		<p>I am a multidisciplinary, scientifically trained programmer, with knowledge of biology, chemistry, and physics, and experience using multiple programming languages.  I enjoy working on interesting projects that require multiple skillsets.  I am currently in the design stages of building an audio mixer, which I intend to allow to interface through minijacks, usb and bluetooth, so that I can mix audio from the different sources that I want to hear, and output to the most appropriate speakers for the situation.</p>
	
        <img src=<?php echo _IMG?>/usk_valley.jpg width=30% class='left'>
        <p>I grew up in South Wales, on a hill overlooking the Usk valley (see left), went to University in Bath and Leicester. I now live in Royston, Herts, and work at the <a href="https://sanger.ac.uk" target="_blank">Wellcome Sanger Institute</a> as a Software Developer.</p>
		<p>I regularly go bouldering and climbing with a friend who is also part of a group with whom I play video games and tabletop games, when I manage to organise them, remotely.  I'm currently trying to organise a campaign of The Wildsea, a setting where people live above the canopy of a forest of enormous trees.</p>
	<p>I play the piano to relax, and I'm looking into learning to play the violin again, which I haven't played for a long time.  I also paint watercolours when I can, below is a painting of my dog, Pixel, who died from old age in June 2024.<p>
	<img src=<?php echo _IMG?>/pixel.jpg width=35% class='right'>

	    
        <script type="text/javascript">
            checkCookies("<?php echo _ROOT?>");
        </script>
	</body>
</html>
