<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("./php/constants.php");
            include(_PHP . "/menus.php");
        
        ?>
		<meta charset="UTF-8">
		<title>Michael Kubiak - Homepage</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Homepage" content="" id="name"/>
		<?php
            echo "<link rel='stylesheet' type='text/css' href='". _CSS ."style.css'>";
            echo "<script src=" . _JS . "menus.js></script>";
            $pages = getMenuLists();
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);?>
        <?php echo "<img src='" . _IMG . "Me.jpg' width = 30% class='right' style='margin-top:1%'>"?>
        <p>This is my website about me, look, thats me, maybe you want to look at some other pages, doody-doody-doody-do.  I need to write more to check how this is going, it should be possible to see whats going on.  I should just have used Ipsum Lorem or whatever it is called I can't remember at the moment.</p>
        <p>This is a new paragraph, hopefully the image will still appear correctly with 2 paragraphs next to it, wouldn't that be nice?</p>
        <p>Oh, excellen, it worked.  I am amazed!</p>
        <p>I'm good at spelling... I meant typing, I'mg reat at that</p>
		
        
	</body>
</html>
