<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("./php/constants.php");
            include(_PHP . "/menus.php");
        
        ?>
		<meta charset="UTF-8">
		<title>MICHAEL KUBIAK - Homepage</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Homepage" content="" id="name"/>
		<?php
            foreach (getFileLists(["css"], _CSS) as $file){
                echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/$file[basename]'>";
            }
            echo "<script src=" . _JS . "/menus.js></script>";
            echo "<script src=" . _JS . "/buttons.js></script>";
            $pages = getFileLists(["phtml", "html"]);
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);
        echo "<img src='" . _IMG . "/Me.png' width = 30% class='right' style='margin-top:1%'>"?>
        <h2>About me</h2>
        
        <p>I am a multidisciplinary, scientifically trained programmer, with knowledge in areas of biology, chemistry, and physics, and experience using multiple programming languages.  I enjoy working on interesting projects, and have a number on the go at present, as you'll see from the appropriate sections of the website.</p>
        <p>I have recently completed my MSc Bioinformatics at the University of Leicester with a Distinction, and I'm actively looking for a job or PhD, particularly in bioinformatics, but I'm open to anything that seems interesting (or even just gives me more experience).</p>
        <p>Currently, I live in South Wales, on a hill overlooking the Usk valley, and break up my days of coding and job applications by taking the dogs for walks through the forest.  I also play the piano to relax me when the project that I am currently working on gets too frustrating.</p>
        <p>In normal times I regularly went bouldering and climbing with a group that I formed.  We also play video games and tabletop games (often with me running them) remotely at present.</p>
        <p>I have also joined a group that is helping to provide food, for people who are shielding or otherwise unable to get it, by packing donated food into weekly or fortnightly parcels that can be delivered to their doorsteps.</p>
        
		
        <div class='bottom screenwidth banner' id=cbanner><p class=banner>This website uses cookies - <a href=.cookies.html style=color:yellow>learn more</a></p><button class=banner onclick="removeElement('cbanner')">OK</button></div>
        <script type="text/javascript">
            checkCookies();
        </script>
	</body>
</html>
