<!DOCTYPE html>
<html lang="en-gb">
    <head>
        <?php 
            include("../../php/constants.php");
            include(_PHP . "/menus.php");
        
        ?>
        <meta charset="UTF-8">
        <title>Michael Kubiak</title>
        <meta name="Projects" content="" id="name"/>
        <?php
            echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/style.css'>";
//            $pages = getMenuLists();
//            $current = getCurrentPage();
        ?>

    </head>
    <body>
        Hello
        <div>
        </div>
        
    </body>
</html>