<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<?php 
            include("../php/constants.php");
            include(_PHP . "/menus.php");
            include(_PHP . "/collapsible.php");
        
        ?>
		<meta charset="UTF-8">
		<title>MICHAEL KUBIAK - Education</title>
		<meta name="Author" content="Michael Kubiak"/>
		<meta name="Education" content="" id = "name"/>
		<?php
			foreach (getFileLists(["css"], _CSS) as $file){
                echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/$file[basename]'>";
            }
			echo "<script src=" . _JS . "/menus.js></script>";
            echo "<script src=" . _JS . "/buttons.js></script>";
            $pages = getFileLists(["phtml"]);
            $current = getCurrentPage();
        ?>
	</head>
	<body>
		<?php createMenuSystem($pages, $current);?>
		<section>
            <?php startCollapsible("bioinf");?>
                <h2 class=sectionheading>MSc Bioinformatics - 2020</h2>
                <p class=place>University of Leicester</p>
                <small id=show>(show)</small>
                <small class=hide id=hide>(hide)</small>
                
            </div>
            <div class=inside>
                <h3>Grade: Pass with Distinction</h3>
                <p>My Masters consisted of three elements: <strong>lectures and coursework</strong>, a <strong>group project</strong>, and an <strong>individual project</strong> supervised by a member of the University of Leicester faculty.</p>
                
                 <hr style="width:10px">
                
                <section>
                    <?php startCollapsible("landc") ?>
                        <h3 class=sectionheading>Lectures and Coursework</h3> 
                        <small id=show>(show)</small>
                        <small id=hide class=hide>(hide)</small>
                    </div>
                    <div class="inside">
                        <p>The <strong>taught</strong> element of the course gave me knowledge of a variety of areas.  There were lectures on proteins, which included protein structure, post-translational modification, visualisation and modelling, as well as methods of determining proteins structure by experiment, such as NMR and X-ray Crystallography.  This module also included assessments on protein sequence analysis.</p>
                        <p>There was also a set of lectures on genes and genomes, which covered genome sequencing techniques (including NGS), transcription and translation, and the enzymes involved, genetic mapping, genome annotation and comparative genomics, and construction of phylogenetic trees.  In this module, the assignments covered comparative genomics and the annotation of novel genome sequences.</p>
                        <p>A number of programming and informatics modules were also a part of the course, with python, java and SQL, as well as a more general algorithms section.  There was also a section on statistical analysis using R, and sample bootstrapping to ensure significance. Many of the people on my course had less experience with programming than I did, and I was able to provide help and advice when asked.
                        </p>
                    </div>
        
                </section>
                
                <hr style="width:10px">
                
                <section>
                    <?php startCollapsible("group")?>
                        <h3 class=sectionheading>Group Project</h3> 
                        <small id=show>(show)</small>
                        <small id=hide class=hide>(hide)</small>
                    </div>
                    <div class="inside">
                        <p>
                        In the <strong>group project</strong>, I was a member of a 4 person group, attempting to replicate and review methods from a gene expression study.  We also compared these methods with other, more recent, pipelines with similar applications.  The pipelines used were all written in, and accessed through, R, and so provided extensive experience in that language.  I also wrote the template for our web page, and used Shiny to generate interactive plots demonstrating our results.  The code repository for this project is available on my GitHub page, at <a href=https://github.com/MichaelKubiak/Group_Project target="_blank">https://github.com/MichaelKubiak/Group_Project</a>, and the report can be viewed <a href= "../Files/gp_report.pdf" target="_blank">here</a>. PLEASE NOTE: the webserver on which the website was displayed was private, so cannot be viewed from outside the University of Leicester.
                        </p>
                    </div>
        
                </section>
                
                <hr style="width:10px">
                
                <section>
                    <?php startCollapsible("indiv")?>
                        <h3 class=sectionheading>Individual Project</h3> 
                        <small id=show>(show)</small>
                        <small id=hide class=hide>(hide)</small>
                    </div>
                    <div class="inside">
                        <p>
                        My <strong>individual project</strong> involved the use of machine learning approaches to annotate protein function from HMMER scores of proteins against the Pfam database.  To train these systems, I used protein annotations from Enzyme.dat, the EC annotation file for Swissprot proteins.  The manipulation of these large databases provided experience of preprocessing techniques, and required extensive use of SPECTRE, an HPC cluster at University of Leicester.  In testing different sets of variables for model training, I had to submit batch jobs to SPECTRE.  This project was mainly written in Python, and the code is available on my GitHub, at <a href=https://github.com/MichaelKubiak/Annotation target="_blank">https://github.com/MichaelKubiak/Annotation</a>.  My report for this project is available from <a href="../Files/ip_report.pdf" target="_blank">here</a>.  
                        </p>
                        <p>
                        I am continuing this project with support from my supervisor, and more about it can be found on the <a href="../Projects/eclassifier.phtml">Enzyme Classifier</a> page.
                        </p>
                    </div>
        
                </section>
            </div>
            
        </section>
        
        <hr style="height:3px; background-color:grey">
        
        <section>
            <?php startCollapsible("natsci")?>
                <h2 class=sectionheading>BSc Natural Sciences - 2017</h2>
                <p class = place>University of Bath</p>
                <small id=show>(show)</small>
                <small id=hide class=hide>(hide)</small>
            </div>
            <div class=inside>
                <h3>Grade: 2:2</h3>
                <p>
                During my undergraduate degree, I took modules in physics, chemistry, and mathematics.  These included, but were not limited to, quantum physics and chemistry, analytical chemistry, Fourier Transforms, electrochemistry, vector calculus, chemistry of porous materials (such as MOFs, COFs, sodalites, etc.), fluid dynamics, and multiple modules about electromagnetism and Maxwell's equations.
                </p>
                <p>
                My final year project involved investigation of the fluorescent properties of sodalites, and solid state synthesis of sodalites with white fluorescence.  The report for this project can be found <a href="../Files/ug_report.pdf" target="_blank">here</a>.
                </p>
                <!--To be expanded once website is complete-->
            </div>
        </section>
        
        <hr style="height:3px; background-color:grey">
        
        <section>
            <?php startCollapsible("school")?>
                <h2 class=sectionheading>AS/A levels - 2012/13</h2> 
                <p class=place>Rougemont School, Newport</p>
                <small id=show>(show)</small>
                <small id=hide class=hide>(hide)</small>
            </div>
            <div class=inside>
                <p>I have A levels in Physics, Chemistry, Maths (all A's) and Further Maths, and AS levels in German and Critical Thinking.</p>
                <p>I also got an A* in a WJEC Extended Project titled "What are Magnetic Resonance Imaging (MRI) and Nuclear Magnetic Resonance (NMR) Spectroscopy and how effective is MRI in the field of diagnostic medicine?"</p>
            </div>
        </section>
        
        <hr style="height:3px; background-color:grey">
        
        <section>
            <?php startCollapsible("sup")?>
                <h2 class=sectionheading>Supplementary Qualifications</h2> 
                <small id=show>(show)</small>
                <small id=hide class=hide>(hide)</small>
            </div>
            <div class=inside>
                <p>
                    I am currently taking a remote cloud computing specialisation course produced by the University of Illinois, as a part of their MSc Computer Science.  It leads to a qualification and can be used as credit towards that degree if I wish. 
                </p>
                <p>
                    I have a Level 2 NVQ in "food and beverage science" which I undertook during my time working at the White Hart Inn.
                </p>
            </div>
        </section>
        
        <hr style="height:3px; background-color:grey">

        <script type="text/javascript">
            checkCookies("<?php echo _ROOT?>");
        </script>
	</body>
</html>
