<!DOCTYPE html>
<html lang="en-gb">
    <head>
        <?php 
            include("../php/constants.php");
            include(_PHP . "/menus.php");
            
        ?>
        <meta charset="UTF-8">
        <title>Michael Kubiak</title>
        <meta name="Homepage" content="" id="name"/>
        <?php
            echo "<link rel='stylesheet' type='text/css' href='" . _CSS . "/style.css'>"
        ?>
        
    </head>
    <body>

        <div>
            
            <?php 
                echo json_encode(getMenuLists(), JSON_HEX_TAG), "<br>";
            ?>
            
        </div>
    </body>
</html>